# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remote_operation2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Widget.CmdTabListWidget import CmdTabListWidget
from Widget.CmdListWidget import CmdListWidget
from Res.QssStyle import *
from Res.img import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1170, 750)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setSpacing(0)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: #0046A5;\n"
"color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButton = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":Res\\cc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(100, 60))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_2.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setIcon(icon)
        self.toolButton_8.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_2.addWidget(self.toolButton_8, 0, 2, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setIcon(icon)
        self.toolButton_3.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_2.addWidget(self.toolButton_3, 0, 3, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setAutoFillBackground(False)
        self.toolButton_6.setIcon(icon)
        self.toolButton_6.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_6.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout_2.addWidget(self.toolButton_6, 0, 4, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setIcon(icon)
        self.toolButton_7.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_2.addWidget(self.toolButton_7, 0, 5, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_2.addWidget(self.toolButton_4, 0, 6, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setIcon(icon)
        self.toolButton_5.setIconSize(QtCore.QSize(100, 60))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_2.addWidget(self.toolButton_5, 0, 7, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 3))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 3))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20,5,0,5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_2.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_3.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_4.setStyleSheet("font: 12pt \"新宋体\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setCheckable(False)
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.label = QtWidgets.QLabel(Form)
        self.label.setFixedHeight(20)
        self.label.setStyleSheet("background-color:#0046A5;\n"
"color: rgb(0, 193, 0);")
        self.label.setObjectName("label")
        # self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 5, 20, 5)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.listWidget = CmdTabListWidget(Form)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 300))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 111111))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 3, 0, 1, 1)
        self.listWidget_2 = CmdListWidget(Form)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 3, 1, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 180))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 3)
        self.gridLayout.addWidget(self.label, 6, 0, 1, 3)

        self.retranslateUi(Form)
        self.beauty_ui()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "远程运维工具"))
        self.toolButton.setText(_translate("Form", "服务器配置"))
        self.toolButton_2.setText(_translate("Form", "命令配置"))
        self.toolButton_8.setText(_translate("Form", "命令分类"))
        self.toolButton_3.setText(_translate("Form", "清除日志"))
        self.toolButton_6.setText(_translate("Form", "安全加密"))
        self.toolButton_7.setText(_translate("Form", "文档帮助"))
        self.toolButton_4.setText(_translate("Form", "版本信息"))
        self.toolButton_5.setText(_translate("Form", "访问我们"))
        self.pushButton_4.setText(_translate("Form", "服务器"))
        self.pushButton_5.setText(_translate("Form", "连接"))
        self.pushButton_6.setText(_translate("Form", "上传文件"))
        self.pushButton_7.setText(_translate("Form", "下载文件"))
        self.pushButton_9.setText(_translate("Form", "交互"))

    def beauty_ui(self):
        self.pushButton.setFixedSize(30, 30)
        self.pushButton_2.setFixedSize(30, 30)
        self.pushButton_3.setFixedSize(30, 30)
        self.pushButton.setStyleSheet(red_light_style)
        self.pushButton_2.setStyleSheet(yellow_light_style)
        self.pushButton_3.setStyleSheet(green_light_style)
        self.textBrowser.setStyleSheet('QTextBrowser{background-color:#3346A5;border:none;color:white;}')#ivory
